### ISSUE TITLE
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 74 has size 3

### ISSUE THREAD

**Issue by gracegliu** [YttriLab/A-SOID#79]
At the Active Learning step, despite appearing to train ~70 iterations of the classifier, upon refresh no results are shown and instead I receive an error. This occurs with my own data as well as with the CALMS21 dataset.

![image](https://github.com/YttriLab/A-SOID/assets/136514149/0adf0332-c95e-4617-9a0d-5fd7081c7436)

I am unable to save anything, and reloading the .ini file and navigating back to the Active Learning step gives me the same error, along with no iterations visible in the dropdown.

![image](https://github.com/YttriLab/A-SOID/assets/136514149/de3578b0-8598-45aa-9f5f-23572e9dd98c)

Here is the .ini of the file using the CALMS21 dataset.
[Project]
PROJECT_TYPE = CALMS21 (PAPER)
PROJECT_NAME = test
PROJECT_PATH = C:\Users\AhmariLab/Desktop/test
FRAMERATE = 30
KEYPOINTS_CHOSEN = nose, neck, hip_left, hip_right, tail_base
EXCLUDE_OTHER = False
FILE_TYPE = npy
INDIVIDUALS_CHOSEN = resident, intruder
CLASSES = attack, investigation, mount, other
MULTI_ANIMAL = True
IS_3D = False

[Data]
DATA_INPUT_FILES = C:\Users\AhmariLab\Desktop\test\task1_classic_classification\task1_classic_classification\calms21_task1_train.npy
LABEL_INPUT_FILES = C:\Users\AhmariLab\Desktop\test\task1_classic_classification\task1_classic_classification\calms21_task1_train.npy
TEST_DATA_INPUT_FILES = C:\Users\AhmariLab\Desktop\test\task1_classic_classification\task1_classic_classification\calms21_task1_test.npy
TEST_LABEL_INPUT_FILES = C:\Users\AhmariLab\Desktop\test\task1_classic_classification\task1_classic_classification\calms21_task1_test.npy

[Processing]
LLH_VALUE = 0.6
ITERATION = 0
MIN_DURATION = 0.4
TRAIN_FRACTION = 0.01
MAX_ITER = 100
MAX_SAMPLES_ITER = 40
CONF_THRESHOLD = 0.5
N_SHUFFLED_SPLIT = None

**Comment by gracegliu** [comment]
I built another model using my own data, and despite not showing the same error, and despite displaying a classifier trained on at least 50 iterations, I am still not able to access any of the iterations and therefore I can't seem to reclassify or use the model to predict anything.

![image](https://github.com/YttriLab/A-SOID/assets/136514149/256d8156-d5f9-49a7-a6c5-05f235a49624)
![image](https://github.com/YttriLab/A-SOID/assets/136514149/cbdd50c9-086e-40df-9845-209c24bb4d41)


[Project]
PROJECT_TYPE = SLEAP
PROJECT_NAME = GL_3-22-24
PROJECT_PATH = C:\Users\AhmariLab/Desktop/GL_asoid_output
FRAMERATE = 40
KEYPOINTS_CHOSEN = BL paw, BR paw, FL paw, FR paw, nose, tailbase
EXCLUDE_OTHER = False
FILE_TYPE = h5
INDIVIDUALS_CHOSEN = single animal
CLASSES = body grooming, face grooming, scratching, other
MULTI_ANIMAL = False
IS_3D = False

[Data]
DATA_INPUT_FILES = labelledforasoid.000_Female1-03042024115222-0000.analysis.h5, labelledforasoid.001_Male 1-03042024124011-0000.analysis.h5, labelledforasoid.002_male2-31124.analysis.h5
LABEL_INPUT_FILES = female1-3424_No focal subject.tsv, male1-3424_No focal subject.tsv, male2-31124_No focal subject.tsv
ROOT_PATH = None

[Processing]
LLH_VALUE = 0.1
ITERATION = 0
MIN_DURATION = 0.1
TRAIN_FRACTION = 0.02
MAX_ITER = 100
MAX_SAMPLES_ITER = 40
CONF_THRESHOLD = 0.5
N_SHUFFLED_SPLIT = None

**Comment by JensBlack** [comment]
Thanks for reporting this issue.

1) Iteration 0 is already a trained iteration, so you should be able to continue working with your results.
Context: Python is counting from 0 upwards.
You can check the next steps, they will give you a red error message if you don't have the trained model.
If that is the case: Please check your project folder, you should only see results of the active learning process if there is a file called iterX.sav.

> Sometimes you need to remove and reupload the config file in order for the underlying app framework to recognize changes.

2) I will look into the error with the test data. This is usually an issue that was fixed a while ago, so I have a good idea where it is likely coming from.

---

Your classifier performs poorly on average, while all classes (except "other" which is not shown in our plots on purpose) are looking good. This could be the result of accidentally not excluding "other" although almost all frames are labeled and the entire behavior reportoire is meant to be within your categories. If you have a small amount of unlabeled frames, e.g., because you missed some during annotations, I recommend excluding other, rather than including it. This should improve your model's performance.

**Comment by JensBlack** [comment]
Unfortunately this step requires users to press the keyboard button "r"/"R" (the letter not the capital form with shift) to manually refresh the app. this is a behavior, that is not present anywhere else in the app and we are working on resolving this. Until then, the app refresh with "r" should be enough to continue with that step. 

Let me know if that works

**Comment by gracegliu** [comment]
Thank you--It worked.
