### ISSUE TITLE
Input variables with inconsistent numbers of samples

### ISSUE THREAD

**Issue by RafaelParker34** [YttriLab/A-SOID#8]
Similar issue to  https://github.com/YttriLab/A-SOID/issues/4 but different causes and cannot fix so far. 

When I go to extract features I always get the same ValueError, the pose estimation and annotation file are matched and the annotation file was exported to 10Hz. 

Specifically, when trying to troubleshoot and use one video that is 23.2 seconds long I get - ValueError: Found input variables with inconsistent numbers of samples: [273, 233].

My current thinking is that this is occurring because of the video framerate is 58.83fps, but ASOiD is averaging it as though it were 50fps. There are 1365 frames in the video, which when divided by the  framerate of 58.83 gives me 23.2 (matching the number on the annotation file), when divided by 50fps however I get 27.3 (matching the first number I get in the error message).

I would rather not re-encode and re-annotate my videos, so is there something I am missing, why does ASOiD seem to not play well with my framerate?

**Comment by JensBlack** [comment]
Hi Rafael,

Thanks for reaching out and using A-SOiD!

Yes, you are correct that this is likely due to a mismatch between the expected framerate and the annotation file being down/upsampled.
Fascinating edge case that you found. Let's verify some things first and then see what we can do to solve this issue:

### Framerate

> Note: The only information A-SOiD receives about the timing between frames in the pose estimation file is from the framerate argument. We use that information to adjust the annotation file to match the original video.

- Are you sure that your framerate is that specific number? 
With a framerate of 58.83 fps / 0,0169981302056774 ms per frame, it is tough to cut a video into equal pieces (frames), so some misalignment will occur in most cases. Most videos have an average framerate across the entire video that is kept at whole numbers (e.g., 30 Hz). 

- In our code, we convert the input framerate to  `int` values; which value did you put in that you got 50 fps? 

### Annotation

> Note: A-SOiD takes the second row of the annotation file (Time column) to get information about the timing between frames during annotation. Depending on your framerate argument, it upsamples the file to match the frames in your pose estimation files.

> There are 1365 frames in the video, which when divided by the framerate of 58.83 gives me 23.2 (matching the number on the annotation file)

- Is your annotation file directly from BORIS, or did you convert it yourself (e.g., by using the example code [HERE](https://github.com/YttriLab/A-SOID/blob/main/docs/export_annotations_to_binary_format.ipynb))?

-  Do you have a file that already contains an annotation for each frame in the pose estimation file?


### First approach to a solution

-  If you have a pose estimation file with a time step of 0,0169981302056774 ms per frame, you could downsample (or upsample) the file to a framerate matching your annotation file closer or into a whole number at least. 

Some context: Our label import recommends 10 Hz export from BORIS because it is more accessible to upsample to 30/60 Hz from this. 10 Hz, however, is only a solution because BORIS does not allow to export with 33,33333333... ms and so on. This, however, requires that the framerate is somehow dividable by the time step to a whole number. If you can find an export time step for BORIS that matches this requirement for your framerate, you can also use that one. 

- If you have an annotation file that has a label for each frame of the pose estimation file, you can alter the timestep that is used when converting into the binary format ([see here](https://github.com/YttriLab/A-SOID/blob/main/docs/export_annotations_to_binary_format.ipynb)).

 This way, you can give A-SOiD that does not require any upsampling.
The current code requires that the upsample rate is exactly 1 to allow this behavior, so please be sure to use a timestep that is as exact as possible. In the meantime, I will check if we can't update the import to allow for cases like yours to be solved by a direct import.

````      
# upsample labels to fit with pose estimation info
sample_rate = 1 / fps
time_step = labels["time"][1] - labels["time"][0]
upsample_rate = time_step / sample_rate
````

### External solutions

- From this [issue](https://github.com/olivierfriard/BORIS/issues/544#issue-1408517745): BORIS might solve that feature request soon, so frame-wise export is possible. This would solve all of our problems at once.

**Comment by RafaelParker34** [comment]
Hi Jens,

Thanks for getting back to me.

> In our code, we convert the input framerate to int values; which value did you put in that you got 50 fps?

I tried a couple ways, with an input of 58fps, 59fps, and 58.83fps (I edited it in the config file to add the decimals). All of them gave me the same result of [273, 233], seemingly reading it as 50fps.

> Is your annotation file directly from BORIS, or did you convert it yourself 

> This way, you can give A-SOiD that does not require any upsampling.

It is directly from BORIS. I attempted to export it at .017 because this is the closest Boris will allow. This resulted in a pose estimation file and annotation file with the same number of frame entries, but it still gave me the same result of [273, 233].

> If you have a pose estimation file with a time step of 0,0169981302056774 ms per frame, you could downsample (or upsample) the file to a framerate matching your annotation file closer or into a whole number at least

I re-enecoded and re-ran through deeplabcut the testing video that I have been using so I could try at 50fps and 60fps. At 50fps, whether I use a BORIS annotation at 10Hz or at 50Hz, I get the same thing. At 60fps I get the ValueError mismatch albeit with different numbers [227,194].

I am really at a loss now. It makes sense that the weird framerate of 58.83 would be an issue, but I don't see why there would still be a mismatch with something cleaner.

**Comment by JensBlack** [comment]
> I re-enecoded and re-ran through deeplabcut the testing video that I have been using so I could try at 50fps and 60fps. At 50fps, whether I use a BORIS annotation at 10Hz or at 50Hz, I get the same thing. 

This is indeed weird. Can you post the full error message (including traceback) and you config?

**Comment by RafaelParker34** [comment]
Sorry, I took a few days away from the project. 
When I came back to it today and ran the same config file I was trying before, to pull the error message for you, it was working. It now works when I use 50Hz video and 10Hz annotation files. I didn't do anything differently, so I don't have any answers, but it is working now, so thanks.

**Comment by JensBlack** [comment]
That's great news to hear. Feel free to reopen this issue if the problem comes back. In the meantime, we have updated A-SOiD and got rid of some other problems. I recommend that you update to the newest version.

I will close this issue as solved.
